import { Language } from '../types';

export const languages: Language[] = [
  {
    code: 'ja',
    name: '日本語',
    texts: {
      title: 'Availability',
      searchParameters: '検索条件',
      period: '期間',
      start: '開始',
      end: '終了',
      currentSelection: '現在の選択',
      minimumDuration: '最小時間',
      timeRestrictions: '時間除外設定',
      before: '以前を除外',
      after: '以降を除外',
      findAvailableTimes: '空き時間を検索',
      searchingCalendar: 'カレンダーを検索中...',
      availableSlots: '空き時間',
      copyAll: 'すべてコピー',
      copied: 'コピー済み',
      noSlotsFound: '空き時間が見つかりませんでした',
      minutes: '分',
      hour: '時間',
      hours: '時間',
      monthNames: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
      weekDays: ['日', '月', '火', '水', '木', '金', '土'],
      dayNames: ['日', '月', '火', '水', '木', '金', '土'],
      // Menu texts
      menu: 'メニュー',
      openMenu: 'メニューを開く',
      userGuide: '使い方ガイド',
      features: '機能について',
      googleCalendarIntegration: 'Googleカレンダー連携',
      autoDetection: '空き時間自動検出',
      oneClickCopy: 'ワンクリックコピー',
      timeSettings: '時間制限設定',
      // Manual page texts
      aboutApp: 'Availabilityについて',
      aboutDescription: 'Availabilityは、Googleカレンダーと連携して空き時間を自動検出し、相手に共有しやすいテキスト形式で出力するWebアプリケーションです。日程調整ツールのような登録負担をかけることなく、効率的に空き時間を共有できます。',
      quickStart: 'クイックスタート',
      selectPeriod: '期間を選択',
      selectPeriodDesc: '開始日時と終了日時を設定します。カレンダーから直接選択できます。',
      setMinDuration: '最小時間を設定',
      setMinDurationDesc: '検索したい空き時間の最小単位を選択します（15分〜90分）。',
      executeSearch: '検索実行',
      executeSearchDesc: '「Find Available Times」ボタンをクリックして空き時間を検索します。',
      copyResults: '結果をコピー',
      copyResultsDesc: '「Copy All」ボタンで全ての空き時間をクリップボードにコピーできます。',
      mainFeatures: '主な機能',
      calendarIntegration: 'カレンダー連携',
      calendarIntegrationDesc: 'Googleカレンダーと安全に連携し、既存の予定を自動で読み取ります。OAuth 2.0による安全な認証で、プライバシーを保護します。',
      autoDetectionFeature: '自動検出',
      autoDetectionDesc: '既存の予定の間にある空き時間を自動で検出し、指定した最小時間以上の空きスロットのみを抽出します。',
      easySharing: '簡単共有',
      easySharingDesc: '検出された空き時間は読みやすいテキスト形式で表示され、ワンクリックでクリップボードにコピーできます。',
      timeRestriction: '時間制限',
      timeRestrictionDesc: '「Time Restrictions」で特定の時間帯のみに絞り込み可能。営業時間内のみの空き時間検索などに便利です。',
      detailedUsage: '詳細な使い方',
      dateSelection: '日時選択',
      dateSelectionDesc: 'カレンダーから開始日と終了日を選択します。各日付の下にある時間入力フィールドで、時刻を15分単位で設定できます。',
      hint: 'ヒント',
      dateHint: '複数日にわたる検索も可能です。例えば、来週1週間の空き時間を一度に検索できます。',
      durationSettings: '最小時間設定',
      durationSettingsDesc: '検索したい空き時間の最小単位を選択します。短い打ち合わせなら15分、しっかりとした会議なら60分以上を選択するのがおすすめです。',
      timeRestrictionsOption: '時間制限（オプション）',
      timeRestrictionsDesc: '「Time Restrictions」セクションを展開すると、検索する時間帯を制限できます。',
      afterTime: '指定時刻以降の空き時間のみ検索',
      beforeTime: '指定時刻以前の空き時間のみ検索',
      example: '例',
      timeRestrictionExample: 'After: 09:00、Before: 18:00 と設定すると、営業時間内（9時〜18時）の空き時間のみが表示されます。',
      resultsManagement: '結果の管理',
      resultsManagementDesc: '検索結果は「Jan 15 (Mon) 09:00 - 10:30」のような読みやすい形式で表示されます。',
      copyAllSlots: '「Copy All」で全ての空き時間をコピー',
      deleteIndividual: '不要な時間帯は個別に削除可能',
      usageTips: '使用上のヒント',
      privacyTitle: 'プライバシーについて',
      privacyDesc: '予定の詳細内容は取得せず、開始・終了時刻のみを使用します。データはサーバーに保存されず、ブラウザ内でのみ処理されます。',
      efficientUsage: '効率的な使い方',
      efficientUsageDesc: '週単位や月単位で検索し、結果をテキストファイルに保存しておくと、複数の相手との日程調整で再利用できて便利です。',
      mobileSupport: 'モバイル対応',
      mobileSupportDesc: 'スマートフォンやタブレットでも快適に使用できます。外出先での急な日程調整にも対応できます。',
      faq: 'よくある質問',
      faqAuth: 'Googleアカウントの認証が必要ですか？',
      faqAuthAnswer: 'はい。Googleカレンダーの予定を読み取るため、Googleアカウントでの認証が必要です。OAuth 2.0による安全な認証を使用しており、カレンダーの読み取り権限のみを要求します。',
      faqMultiCalendar: '複数のカレンダーに対応していますか？',
      faqMultiCalendarAnswer: 'はい、複数のGoogleカレンダーに対応しています。ログイン後、カレンダー選択機能で検索対象とするカレンダーを個別に選択できます。共有カレンダーやサブカレンダーも含め、必要なカレンダーのみを選択することで、より正確な空き時間検索が可能です。',
      faqAllDay: '終日の予定は除外されますか？',
      faqAllDayAnswer: 'はい。終日の予定（祝日、休暇など）は空き時間の計算から除外されます。時刻が設定された予定のみが考慮されます。',
      faqDataStorage: 'データは保存されますか？',
      faqDataStorageAnswer: 'いいえ。すべての処理はブラウザ内で行われ、サーバーにデータは送信・保存されません。ページを閉じると全ての情報は削除されます。',
      support: 'サポート',
      supportDesc: 'ご質問やご要望がございましたら、お気軽にお問い合わせください。より良いサービス提供のため、皆様のフィードバックをお待ちしております。',
      // Help tooltips
      helpPeriod: '期間設定のヘルプ',
      helpPeriodDesc: '検索したい期間の開始日時と終了日時を設定します。\n\n• カレンダーアイコンをクリックして日付を選択\n• 時刻は15分単位で設定可能\n• 複数日にわたる検索も可能',
      helpMinDuration: '最小時間のヘルプ',
      helpMinDurationDesc: '検索結果に表示する空き時間の最小単位を指定します。\n\n• 15分: 短い打ち合わせや電話会議\n• 30分: 通常の会議や面談\n• 60分: 1時間の会議\n• 90分: 長めの会議\n• 120分: 2時間のワークショップや研修\n\n設定した時間より短い空きスロットは除外されます。',
      helpTimeRestrictions: '時間除外設定のヘルプ',
      helpTimeRestrictionsDesc: '毎日の特定の時間帯を除外して検索できます。\n\n• 以前を除外: 指定時刻より前の時間を毎日除外（例：9:00前を除外）\n• 以降を除外: 指定時刻より後の時間を毎日除外（例：21:00以降を除外）\n\n例：夜中や早朝を除外したい場合\n以前を除外: 09:00, 以降を除外: 21:00 と設定すると\n毎日9:00-21:00の間のみ表示されます'
    }
  },
  {
    code: 'en',
    name: 'English',
    texts: {
      title: 'Availability',
      searchParameters: 'Search Parameters',
      period: 'Period',
      start: 'Start',
      end: 'End',
      currentSelection: 'Current Selection',
      minimumDuration: 'Minimum Duration',
      timeRestrictions: 'Time Exclusion Settings',
      before: 'Exclude Before',
      after: 'Exclude After',
      findAvailableTimes: 'Find Available Times',
      searchingCalendar: 'Searching calendar...',
      availableSlots: 'Available Slots',
      copyAll: 'Copy All',
      copied: 'Copied',
      noSlotsFound: 'No available slots found',
      minutes: 'min',
      hour: 'hour',
      hours: 'hours',
      monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
      weekDays: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
      dayNames: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
      // Menu texts
      menu: 'Menu',
      openMenu: 'Open menu',
      userGuide: 'User Guide',
      features: 'Features',
      googleCalendarIntegration: 'Google Calendar Integration',
      autoDetection: 'Auto-detect free time',
      oneClickCopy: 'One-click copy',
      timeSettings: 'Time restriction settings',
      // Manual page texts
      aboutApp: 'About Availability',
      aboutDescription: 'Availability is a web application that integrates with Google Calendar to automatically detect free time slots and output them in an easy-to-share text format. You can efficiently share your availability without the registration burden of scheduling tools.',
      quickStart: 'Quick Start',
      selectPeriod: 'Select Period',
      selectPeriodDesc: 'Set the start and end date/time. You can select directly from the calendar.',
      setMinDuration: 'Set Minimum Duration',
      setMinDurationDesc: 'Select the minimum unit of free time you want to search for (15-90 minutes).',
      executeSearch: 'Execute Search',
      executeSearchDesc: 'Click the "Find Available Times" button to search for free time.',
      copyResults: 'Copy Results',
      copyResultsDesc: 'Use the "Copy All" button to copy all available times to your clipboard.',
      mainFeatures: 'Main Features',
      calendarIntegration: 'Calendar Integration',
      calendarIntegrationDesc: 'Securely integrates with Google Calendar to automatically read existing events. Uses OAuth 2.0 for secure authentication to protect your privacy.',
      autoDetectionFeature: 'Auto Detection',
      autoDetectionDesc: 'Automatically detects free time between existing events and extracts only slots that meet your minimum duration requirement.',
      easySharing: 'Easy Sharing',
      easySharingDesc: 'Detected free times are displayed in a readable text format and can be copied to clipboard with one click.',
      timeRestriction: 'Time Restrictions',
      timeRestrictionDesc: 'Filter to specific time ranges using "Time Restrictions". Useful for finding free time within business hours.',
      detailedUsage: 'Detailed Usage',
      dateSelection: 'Date Selection',
      dateSelectionDesc: 'Select start and end dates from the calendar. Use the time input fields below each date to set times in 15-minute increments.',
      hint: 'Hint',
      dateHint: 'You can search across multiple days. For example, you can search for all free time in the next week at once.',
      durationSettings: 'Duration Settings',
      durationSettingsDesc: 'Select the minimum unit of free time you want to search for. 15 minutes for quick meetings, 60+ minutes for thorough discussions.',
      timeRestrictionsOption: 'Time Restrictions (Optional)',
      timeRestrictionsDesc: 'Expand the "Time Restrictions" section to limit the search time range.',
      afterTime: 'Search only for free time after specified time',
      beforeTime: 'Search only for free time before specified time',
      example: 'Example',
      timeRestrictionExample: 'Setting After: 09:00, Before: 18:00 will only show free time within business hours (9 AM - 6 PM).',
      resultsManagement: 'Results Management',
      resultsManagementDesc: 'Search results are displayed in a readable format like "Jan 15 (Mon) 09:00 - 10:30".',
      copyAllSlots: 'Use "Copy All" to copy all free time slots',
      deleteIndividual: 'Unwanted time slots can be deleted individually',
      usageTips: 'Usage Tips',
      privacyTitle: 'About Privacy',
      privacyDesc: 'Only event start/end times are used, not event details. Data is processed only in your browser and not stored on servers.',
      efficientUsage: 'Efficient Usage',
      efficientUsageDesc: 'Search weekly or monthly and save results to a text file for easy reuse when coordinating with multiple people.',
      mobileSupport: 'Mobile Support',
      mobileSupportDesc: 'Works comfortably on smartphones and tablets. Perfect for scheduling on the go.',
      faq: 'Frequently Asked Questions',
      faqAuth: 'Is Google account authentication required?',
      faqAuthAnswer: 'Yes. Authentication with your Google account is required to read Google Calendar events. We use secure OAuth 2.0 authentication and only request calendar read permissions.',
      faqMultiCalendar: 'Does it support multiple calendars?',
      faqMultiCalendarAnswer: 'Yes, it supports multiple Google calendars. After logging in, you can use the calendar selector to choose which calendars to include in your search. This includes shared calendars and sub-calendars, allowing you to select only the necessary ones for more accurate availability searches.',
      faqAllDay: 'Are all-day events excluded?',
      faqAllDayAnswer: 'Yes. All-day events (holidays, vacations, etc.) are excluded from free time calculations. Only events with specific times are considered.',
      faqDataStorage: 'Is data stored?',
      faqDataStorageAnswer: 'No. All processing is done in your browser, and no data is sent to or stored on servers. All information is deleted when you close the page.',
      support: 'Support',
      supportDesc: 'If you have any questions or requests, please feel free to contact us. We look forward to your feedback to provide better service.',
      // Help tooltips
      helpPeriod: 'Period Settings Help',
      helpPeriodDesc: 'Set the start and end date/time for the search period.\n\n• Click calendar icon to select dates\n• Time can be set in 15-minute increments\n• Multi-day searches are supported',
      helpMinDuration: 'Minimum Duration Help',
      helpMinDurationDesc: 'Specify the minimum duration for available time slots to display.\n\n• 15 min: Quick meetings or phone calls\n• 30 min: Regular meetings or interviews\n• 60 min: 1-hour meetings\n• 90 min: Extended meetings\n• 120 min: 2-hour workshops or training sessions\n\nSlots shorter than the set duration will be excluded.',
      helpTimeRestrictions: 'Time Exclusion Settings Help',
      helpTimeRestrictionsDesc: 'Exclude specific time periods from each day.\n\n• Exclude Before: Exclude time before specified time each day (e.g., exclude before 9:00)\n• Exclude After: Exclude time after specified time each day (e.g., exclude after 21:00)\n\nExample: To exclude nights and early mornings\nSet Exclude Before: 09:00, Exclude After: 21:00\nThis will only show 9:00-21:00 time slots each day'
    }
  }
];